### ISSUE TITLE
Checklist for Factory/Playground: Improvements to "Economics"

### ISSUE THREAD

**Issue by chefboyarsky** [ArtBlocks/artblocks-docs#14]
In the context of a checklist, rather than "Economics", this might be better presented as "Pricing" or "Set Prices"

----

It seems like there could be a variety of considerations expanded on for an "Economics" section (see below) and like it could be refined over time. It's an important topic and seems likely to generate a lot of questions. Consider moving some of this more detailed/supporting information out of the checklist and into an economics.md file

----

**"Consider the overall economics of your project for a successful release"**
- It's not clear what "considering the overall economics" means, especially to someone unfamiliar with the space.
- Examples would be helpful, e.g. "In our experience, projects with a floor price between 0.05 and 0.2 seem to successfully sell through" or "When in doubt, look at floor prices of recent projects" or "We recommend setting an upper limit on your dutch auction price significantly higher than you expect people would want to pay -- for example, we find 6 ETH is a good place for most projects"
- What's a recommended number of tiers for a DA -- or does it depend on the project?
- What is the definition of "successful release" here? Might not be totally obvious to someone new to the space. Is it successful if it sells out within 20 minutes, an hour, day, or week? Are price and time-to-sell-out the only considerations for success, or do you have other examples of what has made for successful projects?

----

**There is a two month cooling period between the end of one project and the start of the next**

It's not totally clear what "the start of the next" means here. Reading this, I would wonder if this refers to:

- When the artist is eligible to submit another application
- When the artist can reach out on Discord and ask to have another project created on the testnet
- When the Art Blocks team will reach out to the artist asking if they have another project ready for submission

Some clarification on what a continued relationship between Artist/Art Blocks looks like after a project ends and the two month clock begins would be helpful. And how formal is the two month clock? Will the artist be told at the end of a project "Okay, you'll be eligible to do X on Y date"?

----

Are dutch auctions the only supported pricing model? Can flat prices be used? Is continuous pricing coming (yes)? Anything else in the works? Elaborating on the available options and answering some FAQs about how pricing works and will work on Art Blocks might be an easy place to point if people ask about those models

**Comment by jakerockland** [comment]
@sarahrossien flagging in case you hadn't yet seen this feedback. Would like to defer to you on how we can best update our docs here, though this bug was originally filed in October, so I know things have shifted a lot since then for the btter regarding the current state of the docs :)

**Comment by jakerockland** [comment]
I think this is probably now resolved with our latest state of updated docs, but please re-open if there is additional clarity needed here @chefboyarsky @sarahrossien @madpinney
