### ISSUE TITLE
Checklist for Factory/Playground: Scheduling and pre-release minting

### ISSUE THREAD

**Issue by chefboyarsky** [ArtBlocks/artblocks-docs#15]
*"you may schedule/announce your release"*

My experience was having the team reach out with some available days and time slots to choose from -- so that might be good to mention as what will likely happen.

How much flexibility do the artists have to schedule their release? Can they say "I'd like to launch it on December 15th at noon, can you pencil me in?" or is this mostly up to when it suits the AB schedule? If the team is willing to work with planning around specific events (which I think is the case, e.g. the recent Rituals release), it might be nice to mention this is an option.

----

Some artists do pre-release mints -- either as gifts for friends/family, for giveaways, for private auctions, etc. It would be good to include some information here before the "Unpausing" section about how this works. You might also mention if there are any functional limitations on tokens before the release begins, e.g. for viewing on AB or OS.

- Can the artist mint one or several tokens? Could they mint the entire set if they'd like to sell it in another marketplace, paying the platform fee for each mint?
- What prices are allowed for pre-mints? My experience was setting it to the floor price of the dutch auction -- but if this is the expectation, would be nice to make it explicit (and to add to this, you may want to include a note on the expected price for Mint 0 as well).

**Comment by jakerockland** [comment]
@sarahrossien flagging in case you hadn't yet seen this feedback. Would like to defer to you on how we can best update our docs here, though this bug was originally filed in October, so I know things have shifted a lot since then for the btter regarding the current state of the docs :)

**Comment by jakerockland** [comment]
I think this is probably now resolved with our latest state of updated docs, but please re-open if there is additional clarity needed here @chefboyarsky @sarahrossien @madpinney
