### ISSUE TITLE
Add charity requirements and supporting information

### ISSUE THREAD

**Issue by chefboyarsky** [ArtBlocks/artblocks-docs#19]
There is a required 25% donation to charity for dutch auctions, but I don't think it's mentioned in the docs. It would be good to include this detail as part of the checklist (choosing a charity) or as part of an economics.md file (if that's split out -- see #14 ). There is a doc pinned to the \#artist-lounge channel -- it would be good to include the doc or a link to it in this repo, or mention in the readme/checklist that it's pinned to that channel so people know where to look.

**Comment by jakerockland** [comment]
@sarahrossien flagging in case you hadn't yet seen this feedback. Would like to defer to you on how we can best update our docs here, though this bug was originally filed in October, so I know things have shifted a lot since then for the btter regarding the current state of the docs :)

**Comment by sarahrossien** [comment]
thanks for flagging! charity info has since been added to the checklist, so closing this out

**Comment by jakerockland** [comment]
> thanks for flagging! charity info has since been added to the checklist, so closing this out

Rad, thank you very much for confirming Sarah! :)
