### ISSUE TITLE
Add to checklist: Have a funded wallet

### ISSUE THREAD

**Issue by DLR91** [ArtBlocks/artblocks-docs#23]
Artists sometimes do not have enough ETH in their wallets to submit transactions. Please add a line to the checklist recommending a sufficient amount of ETH in their wallet in case gas is extremely high.

**Comment by mbisaga** [comment]
What's a sufficient amount of ETH these days? @jakerockland @DLR91

**Comment by cooper-temple** [comment]
added and submitted for publishing!

**Comment by jakerockland** [comment]
Thanks @cooper-temple :) your change should be merged/public now.
