### ISSUE TITLE
Issue of Random class in README

### ISSUE THREAD

**Issue by baocancode** [ArtBlocks/artblocks-docs#31]
Hi,

I see this line in the Random class:

```
let a = parseInt(uint128Hex.substr(0, 8, 16))
```

Should it be `parseInt(uint128Hex.substr(0, 8), 16)` as 16 is the radix param of parseInt (substr has only 2 params)? Same issue for the next 3 lines that have `parseInt(uint128Hex.substr`.

**Comment by jakerockland** [comment]
> Hi,
> 
> I see this line in the Random class:
> 
> ```
> let a = parseInt(uint128Hex.substr(0, 8, 16))
> ```
> 
> Should it be `parseInt(uint128Hex.substr(0, 8), 16)` as 16 is the radix param of parseInt (substr has only 2 params)? Same issue for the next 3 lines that have `parseInt(uint128Hex.substr`.

Yes! Thank you very much. We resolved this and announced to our artists, but forgot to clean up the Github issue here. Marking this as resolved :)
