### ISSUE TITLE
Upgrade to Retype docs

### ISSUE THREAD

**Issue by geoffreymcgill** [ArtBlocks/artblocks-docs#37]
Upgrading to [Retype](https://retype.com/) from GitBook is super simple.

I [forked](https://github.com/geoffreymcgill/artblocks-docs) this docs project and published a live demo at https://geoffreymcgill.github.io/artblocks-docs hosted using GitHub Pages. 

See PR #38.

Some benefits of the upgrade would include:

- This GitHub repo becomes the _source of truth_ for your docs website content
- Your content is not stored within a proprietary system
- Accept community contributions via GitHub
- Reference your content in Issues, Discussions, and PR's
- Self-host your docs website using GitHub Pages (or anything else)
- Remove the `Powered by` logo
- Lightning-fast performance
- Dark mode!!
- Free

If you are interested in upgrading to Retype, it's super easy, although a couple of configurations would be required. I can easily step you through these minor changes, which should only take a few minutes to complete. The changes would be:

1. Configure this repo to self-host using GitHub Pages
2. Update the `docs.artblocks.io` domain DNS to point to GitHub Pages

I tried to clean up the docs from what was created by GitBook, but I would love to take another pass through everything. Normalizing some of the Markdown formatting and fine-tuning the document structure would be a nice enhancement. As well, there are several handy UI [components](https://retype.com/components/) within Retype that we could take advantage of. If you are interested, just let me know.

Hope this helps.

**Comment by jakerockland** [comment]
This was done in #38 :) thank you very much @geoffreymcgill for the contribution!
