### ISSUE TITLE
"If you made it this far, we have probably requested a project name and an ethereum address from you" - But you didn't :)

### ISSUE THREAD

**Issue by greenido** [ArtBlocks/artblocks-docs#9]
I've connected my Metamask (and validate that I have few ETH on Ropsten.
However, I don't see any please to 'add' or 'edit' my project and upload the script.

<img width="736" alt="Screen Shot 2021-09-15 at 16 33 48" src="https://user-images.githubusercontent.com/61472/133526489-6511b77f-e666-4072-bca9-d13bd40129cc.png">

What am I missing?

**Comment by jakerockland** [comment]
I think this should be made more clear now with update in #10. Closing.
